### ISSUE TITLE
运行后提示找不到process

### ISSUE THREAD

**Issue by heckerstone** [MJx0/AndKittyInjector#1]
I: Couldn't find process id of 20273

**Comment by heckerstone** [comment]
app进程如下
20273 u0_a196      10 -10 1.3G  89M  49M S  0.0   2.3   0:10.30 com.chelly.yuheshui

**Comment by MJx0** [comment]
> app进程如下 20273 u0_a196 10 -10 1.3G 89M 49M S 0.0 2.3 0:10.30 com.chelly.yuheshui

Use process name not id
./injector com.chelly.yuheshui libpath
