### ISSUE TITLE
An error occurred when I injected in Android

### ISSUE THREAD

**Issue by SKININ** [MJx0/AndKittyInjector#10]
An error occurred when I injected in Android

I: Library Path: /data/local/tmp/libS.so
I: Use memfd dlopen: 0
I: Hide lib from maps: 0
I: Hide lib from solist: 0
I: Use app watch: 0
I: Inject delay: 0
I: inject_lib: Stopped target process threads.
I: inject_lib: Attaching to target process...
I: inject_lib: Attached successfully.
I: injectLibrary: [native=arm64 | lib=arm64].
I: injectLibrary: lib handle = 0x0.
I: injectLibrary: lib Base = 0x0.
E: injectLibrary: failed )':
E: injectLibrary: calling dlerror...
E: injectLibrary: dlopen failed: couldn't map "/data/local/tmp/libS.so" segment 1: Permission denied
I: inject_lib: Killing target process...
E: Injection failed.

**Comment by SKININ** [comment]
Sorry for forgetting to mention the environment, Xiaomi 12s, Android 13

**Comment by MJx0** [comment]
use memfd or disable selinux

**Comment by SKININ** [comment]
Thank
