### ISSUE TITLE
Couldn't initialize injector

### ISSUE THREAD

**Issue by slavadynasty** [MJx0/AndKittyInjector#5]
E: KittyInjector: Failed to find syscall, remote lib not found. 
E: KittyInjector: Failed to initialize remote syscall.

im use ld emulator

**Comment by MJx0** [comment]
Did you enable root in your emulator settings?

**Comment by slavadynasty** [comment]
root is enabled, magisk delta is installed. injecting from termux with root

**Comment by MJx0** [comment]
Which architecture did you use for the injector?
For emulators If your target app is 64bit then use x86_64, If 32bit use x86

**Comment by slavadynasty** [comment]
application and library are equal to arm7

**Comment by slavadynasty** [comment]
I changed the arch of the app with this script
`pkg=com.YonoProduction.ProjectEvolution
pm path $pkg|sed -E  's/(.*):(.*)/\2/'|xargs pm install -r --abi armeabi-v7a
sleep 1
echo "Installed"

`

**Comment by slavadynasty** [comment]
hide inject not working

W: injectLibrary: Library EMachine is not native.
I: injectLibrary: [native=0x3 | lib=0x28].
I: injectLibrary: Searching for native bridge...
I: injectLibrary: Found native bridge "libhoudini.so" version 3.
I: injectLibrary: lib handle = 0xd1d75400
I: Injection took 14.872076 MS.
I: Injection successed.

**Comment by MJx0** [comment]
https://github.com/MJx0/AndKittyInjector/blob/27de6040a0a1b73fce824fef587af7dadf7f7b6e/AndKittyInjector/src/Injector/KittyInjector.cpp#L169

-hide is not implemented for emulated injection yet, I'm still working on it
