### ISSUE TITLE
执行完命令后 有几率卡主

### ISSUE THREAD

**Issue by wangchuanlai** [MJx0/AndKittyInjector#7]
环境 雷电模拟器
I: inject_lib: Stopped target process threads.
I: inject_lib: Attaching to target process...
I: inject_lib: Attached successfully.
I: injectLibrary: [native=x86 | lib=arm].
W: injectLibrary: Library EMachine is not native.
I: injectLibrary: Searching for NativeBridge implementation...
I: injectLibrary: Found NativeBridge "libhoudini.so" version 3.
I: emuInject: Using NativeBridge namespace (3).

**Comment by wangchuanlai** [comment]
卡在这里就不动了 同时进程也卡主

**Comment by MJx0** [comment]
https://github.com/MJx0/AndKittyInjector/blob/520da9a3738f504724bcd6a26d2d9122b748bb95/AndKittyInjector/src/Injector/KittyInjector.cpp#L299

**Comment by MJx0** [comment]
What's the problem?
