### ISSUE TITLE
Couldn't find function

### ISSUE THREAD

**Issue by kitzeo** [MJx0/AndKittyInjector#9]

**Comment by MJx0** [comment]
Check your system libraries at /system/libs
Is libart.so available? If yes then check the symbol JNI_GetCreatedJavaVMs if its available inside of it. You can use ELFViewer or IDA, ghidra and many other tools to view ELF symbols.

**Comment by kitzeo** [comment]
I found and used JNI_GetCreatedJavaVM inside libinjtest.so but when using AndKittyInjector this function is not found outside
